# Generated by Django 5.2.2 on 2025-06-10 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Voucher')),
                ('animal_type', models.CharField(choices=[('kambing', 'Kambing'), ('sapi', 'Sapi'), ('domba', 'Domba'), ('kerbau', 'Kerbau')], max_length=20, verbose_name='Jenis Hewan')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('mosque', models.CharField(max_length=200, verbose_name='Masjid')),
                ('schedule_date', models.DateField(verbose_name='Tanggal Penyembelihan')),
                ('schedule_time', models.TimeField(verbose_name='Waktu Penyembelihan')),
                ('total_vouchers', models.IntegerField(default=0, verbose_name='Total Voucher')),
                ('remaining_vouchers', models.IntegerField(default=0, verbose_name='Sisa Voucher')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='berbagikurban.voucher')),
            ],
            options={
                'verbose_name': 'Klaim Voucher',
                'verbose_name_plural': 'Klaim Vouchers',
                'unique_together': {('voucher', 'user')},
            },
        ),
    ]
